title: "Miao Zhang"
description: "Welcome to my personal website"
theme: "minimal-mistakes-jekyll"
url: "https://miaozhang2025.github.io"  # Replace with your URL
# Social media links
social_links:
  linkedin: "https://www.linkedin.com/in/miao-zhang-7630a2203/"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=WzfvoPkAAAAJ"
