title: "Miao Zhang"
description: "Welcome to my personal website"
#theme: "minimal-mistakes-jekyll"
theme: "jekyll-theme-primer"
url: "https://miaozhang2025.github.io"  # Replace with your URL
baseurl: "https://miaozhang2025.github.io/2024/01/01/2024-AGU/"
author:
  name: "Miao Zhang"
  avatar: /assets/images/Miao.jpg  # Path to your image
  avatar_size: 100                      # Adjust the size of the image
head:
  - "<link rel='stylesheet' href='/assets/css/style.css'>"

# Social media links
social_links:
  linkedin: "https://www.linkedin.com/in/miao-zhang-7630a2203/"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=WzfvoPkAAAAJ"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5  # Pagination for blog posts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
